jqassistant:
  plugins:
    - group-id: org.jqassistant.plugin
      artifact-id: jqassistant-plantuml-report-plugin
      version: 2.0.1
  scan:
    include:
      files:
        - src/main/java
        - src/test/java
        - target/classes
        - target/test-classes
  analyze:
    report:
      warn-on-severity: MINOR
      fail-on-severity: BLOCKER
      continue-on-failure: false
      create-archive: true
    groups:
      - AcousticRules
