

jqassistant:
  plugins:
    - group-id: org.jqassistant.plugin
      artifact-id: jqassistant-plantuml-report-plugin
      version: 2.0.1
    - group-id: org.jqassistant.plugin
      artifact-id: jqassistant-cyclonedx-plugin
      version: 1.0.0
    - group-id: org.jqassistant.plugin
      artifact-id: jqassistant-c4-plugin
      version: 2.0.0

  scan:
    include:
      files:
        - src/main/java
        - src/test/java
        - target/classes
        - target/test-classes
        - cyclonedx:sbom::target/bom.xml
        - cyclonedx:sbom::target/bom.json
        - src/docs/c4/
  analyze:
    rule-parameters:
      rootPackage: com.framstag.acousticrules
    report:
      warn-on-severity: MINOR
      fail-on-severity: BLOCKER
      continue-on-failure: false
      create-archive: true
    groups:
      - AcousticRules
