name: Ubuntu Latest using JDK 17 and Maven

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: ubuntu-latest+JDK17+mvn
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with maven
        run:  mvn --batch-mode --update-snapshots verify
      - name: Static code analysis using Sonar
        run:  mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Framstag_acousticrules
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Release
        uses: ncipollo/release-action@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          allowUpdates: true
          body: "Release of the latest code in main"
          draft: false
          prerelease: true
          generateReleaseNotes: false
          name: latest
          removeArtifacts: true
          replacesArtifacts: true
          tag: latest
          artifacts: "target/acousticrules-jar-with-dependencies.jar"